### BUILD ###
FROM python:3.12-slim AS build

WORKDIR /App

# Avoid pyc files
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --prefix=/install -r requirements.txt

### FINAL ###
FROM python:3.12-slim

WORKDIR /App

# Bring in installed packages from build stage
COPY --from=build /install /usr/local

# Copy application code
COPY . .

# Expose port 8000 for the application
EXPOSE 8000

# Start the application
CMD sh -c "python manage.py collectstatic --noinput && gunicorn aether.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 1"
